### ISSUE TITLE
Jakarta release has wrong OSGi Bundle-SymbolicName

### ISSUE THREAD

**Issue by rfelcman** [jakartaee/servlet#224]
Jakarta release of this API has wrong value of OSGi Bundle-SymbolicName in MANIFEST.MF.
Current value is _javax.servlet-api_ but expected value could be _jakarta.servlet-api_ .

**Comment by markt-asf** [comment]
That value is correct for the current release. It is expected to be changed for the next release:
See https://github.com/eclipse-ee4j/ee4j/issues/34
