### ISSUE TITLE
Clarify behaviour of HttpServletMapping.getMatchValue()

### ISSUE THREAD

**Issue by lachlan-roberts** [jakartaee/servlet#316]
The javadoc for `HttpServletMapping.getMatchValue()` says 
> If the getMappingMatch value is CONTEXT_ROOT or DEFAULT, this method must return the empty string. If the getMappingMatch value is EXACT, this method must return the portion of the path that matched the servlet, omitting any leading slash. If the getMappingMatch value is EXTENSION or PATH, this method must return the value that matched the '*'.

It says the leading slash should be omitted for `EXACT` matches, but it does not say that for `EXTENSION` or `PATH`. So if we had an `EXTENSION` mapping `*.ts` and had a request at `/a.ts`, then the javadoc seems to indicate that the leading slash should be included as it matched the `'*'`. 

There is TCK test `com/sun/ts/tests/servlet/api/javax_servlet_http/httpservletrequest40/Client.java#httpServletMappingTest2` which tests that the leading slash was not included and we get a matchValue of just `a`.

If the TCK has the correct behaviour I think the javadoc should be more clear about when the leading slash is omitted for matchValue.

**Comment by arjantijms** [comment]
Good point. There's a table in the javadoc that clearly doesn't show the leading slash, but this should be in the javadoc as well. Let's clarify this for Servlet 6.0.
