### ISSUE TITLE
Add overload to setCharacterEncoding supporting Charset

### ISSUE THREAD

**Issue by Thihup** [jakartaee/servlet#415]
In JDK, a lot of methods that supported String as charset got overloads to support the `java.nio.charset.Charset`. It makes the lookup faster because it doesn't require a parsing of the String to know if it supported.

One example of this would be the methods `ServletRequest.setCharacterEncoding` and `ServletResponse.setCharacterEncoding`.

Maybe add these overloads as default methods.

**Comment by gregw** [comment]
I think this is a good idea. Want to provide a PR?
