### ISSUE TITLE
Compatibility certification request for EE4J implementation of Jakarta Servlet 6

### ISSUE THREAD

**Issue by arjantijms** [jakartaee/servlet#464]
- [x] Organization Name ("Organization") and, if applicable, URL
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
  [Eclipse Glassfish 7.0.0-M4](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/7.0.0-M4/glassfish-7.0.0-M4.zip)
- [x] Specification Name, Version and download URL
  [Jakarta Servlet 6.0](https://jakarta.ee/specifications/servlet/6.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
  [Jakarta Servlet TCK, 6.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-servlet-tck-6.0.0.zip), SHA-256: ` ad366770f8214970e7d007d64c86959f930b201a0dbce7bf115825ed9f7169fa`
- [x] Public URL of TCK Results Summary
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-servlet/6.0/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements
  None
- [x] Java runtime used to run the implementation
  OpenJDK 11.0.2, 17.0.1, 18-ea
- [x] Summary of the information for the certification environment, operating system, cloud, ...
  Debian GNU/Linux 10
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by markt-asf** [comment]
Approved.

**Comment by ivargrimstad** [comment]
Sha256 does not match the staged TCK.
$ sha256sum jakarta-servlet-tck-6.0.0.zip 
e9bfc33bd3974529b4f91cfde993bd754256fbdb7af2c11d50d37df467131fb6  jakarta-servlet-tck-6.0.0.zip

**Comment by arjantijms** [comment]
@ivargrimstad the TCK was run against GF at the 20th, but it seems the TCK was updated again on the 26th:

```
Date and size: date: 2022-04-26 05:02:31.000000000 +0000, size(b): 20149135
SHA256SUM: e9bfc33bd3974529b4f91cfde993bd754256fbdb7af2c11d50d37df467131fb6
```

**Comment by ivargrimstad** [comment]
Yes, that's usually the case. Anyway, the CCR submitted with results from running the correct version of the TCK. If you have a CI job updating the TCK in the /staged folder, you need to turn that off or move the file to a promoted folder. That is the one that will be published on the Spec page. The SHA must match this one, otherwise, the CCR is not valid.

**Comment by arjantijms** [comment]
I'm running the TCK again right now. It will take about two more hours. The JDK 18 run already passed with 'e9bfc33bd3974529b4f91cfde993bd754256fbdb7af2c11d50d37df467131fb6':

https://ci.eclipse.org/servlet/job/2.1_servlet-run-tck-against-staged-build/6/artifact/servlet-tck/bin/summary.txt

**Comment by ivargrimstad** [comment]
> I'm running the TCK again right now. It will take about two more hours. The JDK 18 run already passed with 'e9bfc33bd3974529b4f91cfde993bd754256fbdb7af2c11d50d37df467131fb6':
> 
> https://ci.eclipse.org/servlet/job/2.1_servlet-run-tck-against-staged-build/6/artifact/servlet-tck/bin/summary.txt

When you're done, update the SHA, and make sure the TCK isn't updated going forward. Then we're all good :)

**Comment by arjantijms** [comment]
I created this issue to stop the Servlet TCK from being updated: https://github.com/eclipse-ee4j/jakartaee-tck/issues/949

**Comment by marceloancelmo** [comment]
I just checked and it is all right
$ sha256sum.exe jakarta-servlet-tck-6.0.0.zip
e9bfc33bd3974529b4f91cfde993bd754256fbdb7af2c11d50d37df467131fb6 *jakarta-servlet-tck-6.0.0.zip

Will follow up on the ballot
