### ISSUE TITLE
[TCK Challenge] invalidateHttpSessionxTest

### ISSUE THREAD

**Issue by mnriem** [jakartaee/servlet#486]
I have a TCK challenge for the invalidateHttpSessionxTest.

See https://github.com/jakartaee/platform-tck/blob/b23c9554913750a532fd60596b09254a8c7340a0/src/com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpsessionx/URLClient.java#L306 

The Piranha project delivers a Servlet container that returns “null” for the ServletContext.getContext(String uripath) which is
allowable as per https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/servletcontext#getContext(java.lang.String) 

As the test in question assumes that a ServletContext is returned it fails.

**Comment by arjantijms** [comment]
As far as I remember this was discussed before and indeed said to be an invalid test.

If the `null` is returned, the test should simply pass.

**Comment by markt-asf** [comment]
Seems reasonable to me. The test can be excluded for now and we'll fix it for 6.1.

**Comment by mnriem** [comment]
@markt-asf What is the status of this one?

**Comment by markt-asf** [comment]
See previous comment.

**Comment by mnriem** [comment]
@markt-asf Can we close this out?

**Comment by mnriem** [comment]
@markt-asf Should this be closed out?

**Comment by stuartwdouglas** [comment]
This has been fixed, so we should close this.
