### ISSUE TITLE
[TCK Challenge] dispatchAfterCommitTest4

### ISSUE THREAD

**Issue by mnriem** [jakartaee/servlet#489]
The com/sun/ts/tests/servlet/api/jakarta_servlet/dispatchtest/URLClient.java#dispatchAfterCommitTest4 fails,
because it is using ServletContext.getContext(path) and in Piranha it returns null (which is allowed) and thus the test fails.

See https://github.com/jakartaee/platform-tck/blob/b23c9554913750a532fd60596b09254a8c7340a0/src/com/sun/ts/tests/servlet/api/jakarta_servlet/dispatchtest/DispatchTestServlet.java#L1079  for the offending line.

**Comment by mnriem** [comment]
@markt-asf What is the status of this issue?

**Comment by markt-asf** [comment]
The test can be excluded for now and we'll fix it for 6.1.

**Comment by olamy** [comment]
see https://github.com/jakartaee/servlet/pull/553

**Comment by mnriem** [comment]
@olamy  @markt-asf Can I close this one out now?
