### ISSUE TITLE
[TCK Challenge] dispatchAfterCommitTest5

### ISSUE THREAD

**Issue by mnriem** [jakartaee/servlet#490]
I have a TCK challenge for the dispatchAfterCommitTest5.

See [https://github.com/jakartaee/platform-tck/blob/b23c9554913750a532fd60596b09254a8c7340a0/src/com/sun/ts/tests/servlet/api/jakarta_servlet/dispatchtest/DispatchTestServlet.java#L1087](https://github.com/jakartaee/servlet/issues/%22)

The Piranha project delivers a Servlet container that returns “null” for the ServletContext.getContext(String uripath) which is
allowable as per [https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/servletcontext#getContext(java.lang.String)](https://github.com/jakartaee/servlet/issues/%22)

As the test in question assumes that a ServletContext is returned it fails.

**Comment by mnriem** [comment]
@markt-asf What is the status of this issue?

**Comment by markt-asf** [comment]
The test can be excluded for now and we'll fix it for 6.1.

**Comment by olamy** [comment]
see https://github.com/jakartaee/servlet/pull/553

**Comment by mnriem** [comment]
@markt-asf @olamy Can this be closed out?

**Comment by olamy** [comment]
fixed with #553
