### ISSUE TITLE
Is the maintenance plan updated for jakarta servlet-4.0.x?

### ISSUE THREAD

**Issue by Triste-001** [jakartaee/servlet#498]
jakarta servlet is a good product, many of our products rely on it, but our company uses JDK8 and tomcat9 for development, while the latest jakarta servlet-6.0.0 requires JDK11. We'd like to know if there's a maintenance upgrade plan for jakarta servlet4.0.x

**Comment by stuartwdouglas** [comment]
There will not be an upgrade to the 4.x spec.

This is an API so 'decay' is not really an issue. If you want an updated version you need to move to updated Servlet containers and JDK.

**Comment by Triste-001** [comment]
thank you for your answer
