### ISSUE TITLE
Add PATCH support in HttpServlet.java

### ISSUE THREAD

**Issue by garydgregory** [jakartaee/servlet#506]
Hi All,

I would like to use HTTP PATCH. Is this project interested in a PR for https://github.com/jakartaee/servlet/blob/master/api/src/main/java/jakarta/servlet/http/HttpServlet.java? Is there a reason it is not supported out of the box?

**Comment by markt-asf** [comment]
Duplicates #113.

No reason a PR that addresses #113 can't be included in 6.1.

**Comment by garydgregory** [comment]
Hi @markt-asf 

I'm looking for guidance or process documentation to manage expectations on my end as to when this change would make it in any kind of release, such that, eventually, it ends up in Eclipse Jetty.

TY for your help and guidance.

**Comment by markt-asf** [comment]
You'll have to ask Jetty if you want details of Jetty release plans.

This change is going to be included in Servlet 6.1 which I currently expect to be released in Q4 this year but that depends on Jakarta EE 11 sticking to a release schedule of Q1 2024.

If there is demand, we can produce a Servlet 6.1 milestone release at pretty much any point.
