### ISSUE TITLE
[TCK Challenge] check for object identity in dispatcher test

### ISSUE THREAD

**Issue by janbartel** [jakartaee/servlet#524]
**Challenged tests:**

`com/sun/ts/tests/servlet/spec/requestdispatcher/URLClient.requestDispatcherNoWrappingTest`

**TCK Version:**

servlet-tck-6.0.1

**Tested Implementation:**

Jetty

**Description:**

Version 6 of the Servlet Spec removed the requirement for object identity during dispatch, see #411.  However, the above test is still included in the tck.

**Comment by markt-asf** [comment]
Looks reasonable to me. I'll leave it a little while to allow others to comment but my expectation at this point is that:
- the challenge will be accepted
- the test can be added to the ignore list for now
- the test will be removed for the Servlet 6.1 TCK

**Comment by stuartwdouglas** [comment]
Seems reasonable to me.
