### ISSUE TITLE
Why does this library exist?

### ISSUE THREAD

**Issue by juman123** [jakartaee/servlet#535]
Or put another way, _"Why couldn't Jetty still be based on the standard JDK Servlet API?"_

I upgraded from Jetty v9 to Jetty v11 and had to go through my app replacing standard Servlet things with Jakarta Servlet things.

It was quite a bit of work, and left me wondering why it had to be done.

**Comment by stuartwdouglas** [comment]
Oracles legal department would not let anyone continue to use the javax namespace. There are lots of articles about it, e.g. https://blogs.oracle.com/javamagazine/post/transition-from-java-ee-to-jakarta-ee.

**Comment by juman123** [comment]
Alright, thanks for the information
