### ISSUE TITLE
There are a lot of redundant keywords that need to be removed in the jakarta.servlet-api.

### ISSUE THREAD

**Issue by OnlyWick** [jakartaee/servlet#556]
For example: https://github.com/jakartaee/servlet/blob/master/api/src/main/java/jakarta/servlet/http/HttpServletRequest.java

There is no need to include the keywords public, static, final in `interface`.

**Comment by OnlyWick** [comment]
If any changes are needed, please assign them to me. : )

**Comment by markt-asf** [comment]
Fixed by PR #557 / PR #566
