### ISSUE TITLE
tests should not be in the jakarta package

### ISSUE THREAD

**Issue by lukasj** [jakartaee/servlet#615]
JESP explicitly prohibits usage of `jakarta` package namespace to everything but APIs, therefore (unit) tests must be moved to a different package

**Comment by arjantijms** [comment]
Doesn't the persistence and rest etc TCKS do the same thing?

E.g. rest is "ee.jakarta.tck.ws.rs", persistence is "ee.jakarta.tck.persistence", or do you mean something else?

**Comment by olamy** [comment]
https://github.com/jakartaee/servlet/tree/master/api/src/test/java/jakarta/servlet
are unit tests but those are not distributed.
tck is under `servlet.tck` https://github.com/jakartaee/servlet/tree/master/tck/tck-runtime/src/main/java/servlet/tck

**Comment by lukasj** [comment]
> Doesn't the persistence and rest etc TCKS do the same thing?
> 
> E.g. rest is "ee.jakarta.tck.ws.rs", persistence is "ee.jakarta.tck.persistence", or do you mean something else?

`jakarta` package namespace and `ee.jakarta` package namespace are different, aren't they?

**Comment by lukasj** [comment]
JESP 1.4:
> Use of the jakarta namespace is limited to API artifacts (all API jars, javadoc, and schema namespaces). It must not be used for any deployment, including applications, TCKs, tools, libraries or any other assets produced by Specification Projects.

so even unit tests which are currently in the `jakarta.servlet` package need to be in a different package.

**Comment by olamy** [comment]
JESP 1.4:

> Use of the jakarta namespace is limited to API artifacts (all API jars, javadoc, and schema namespaces). It must not be used for any deployment, including applications, TCKs, tools, libraries or any other assets produced by Specification Projects.

Sure but this is still confusing. 
This is saying ` It must not be used for any deployment` and as I said unit tests not deployed but only part of the source tree.

**Comment by arjantijms** [comment]
> jakarta package namespace and ee.jakarta package namespace are different, aren't they?

I hear you, thanks for the clarification. It's about packages starting with jakarta, and not those containing jakarta somewhere in the middle.
