### ISSUE TITLE
Blocker for starting EE 11 ballot: TCK user guide, and two folders with a tck-runtime.jar and a tck-utils.jar. I guess an assembly file is needed to create a zip file with those two artefacts, and then we have to add a basic user guide still.

### ISSUE THREAD

**Issue by edburns** [jakartaee/servlet#617]
Copied from https://github.com/jakartaee/specifications/pull/717#issuecomment-2065294130.

> The TCK is currently only available in a staged Maven repo. This review should not progress until a 'standard' TCK zip is staged to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee11/staged/

Hi, I took a look at the current TCK. At the last platform call we thought it was just a matter of copying a zip file from Maven to the download location, but there's a little bit more needed.

There is not really a "standard" TCK zip, unfortunately, but maybe REST and Pages are good examples. They both contain folder as follows:

```
artefacts
    jakarta-foo-tck-version.jar
    jakarta-foo-tck-version-sources.jar
docs
    html-usersguide
    pdf-usersguide
    assertions
    [...]
LICENSE.md
```

**Comment by markt-asf** [comment]
Fixed by #618
