### ISSUE TITLE
Finalize the release of Jakarta Servlet 6.1

### ISSUE THREAD

**Issue by ivargrimstad** [jakartaee/servlet#651]
Please complete the following steps to finalize the release

 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] if XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from `Draft` to `Final`.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by arjantijms** [comment]
https://projects.eclipse.org/projects/ee4j.servlet/releases/6.1 linked from https://jakarta.ee/specifications/servlet/6.1/ gives a 404. The record is at https://projects.eclipse.org/projects/ee4j.servlet/releases/6.1.0. 

Perhaps everything should have been 6.1 from the start, but alas. I'll do a PR to update the link.

**Comment by markt-asf** [comment]
> Perhaps everything should have been 6.1 from the start, but alas. I'll do a PR to update the link.

Can we not edit the release record to 6.1 ?

**Comment by ivargrimstad** [comment]
> Waiting on [the schemas project](https://github.com/jakartaee/jakartaee-schemas/pull/48) to merge the necessary schema updates.

Done

**Comment by ivargrimstad** [comment]
> > Perhaps everything should have been 6.1 from the start, but alas. I'll do a PR to update the link.
> 
> Can we not edit the release record to 6.1 ?

That should be possible. And if it, for some reason isn't, then just fix the link so we avoid 404's. Either way is fine

**Comment by markt-asf** [comment]
Release record updated to 6.1

**Comment by markt-asf** [comment]
PR submitted to fix/update the schemas: https://github.com/jakartaee/jakarta.ee/pull/1939

**Comment by markt-asf** [comment]
Published schema have been updated.
