### ISSUE TITLE
Version javax.servlet-api 4.0.1 still can be used

### ISSUE THREAD

**Issue by bharathmit** [jakartaee/servlet#675]
We don't intend to switch to the newest version of jakarta.servlet-api jar; we are currently utilizing 4.0.1 javax.servlet-api.

We observed that the 4.0.1 has no vulnerabilities in the jars. So can we still used in code?  Also may i know the end of life/support (EOL/EOS) of the 4.0.1 version?

**Comment by markt-asf** [comment]
Support questions regarding the older versions of the API in the javax package should be directed to the [JCP](https://jcp.org/en/home/index).

That said, I would be amazed if there was a maintenance release of any of the Java EE APIs.

Finally, you should really be directing your question to the vendor of the Servlet container you are using.
