### ISSUE TITLE
Should the new Servlet 6.1 `jakarta.servlet.error.method` attribute be added to `Table 10-1 Request Attributes and their types`?

### ISSUE THREAD

**Issue by pnicolucci** [jakartaee/servlet#682]
Currently, the table only lists the new Servlet 6.1 `jakarta.servlet.error.query_string` attribute but is missing the `jakarta.servlet.error.method` attribute.

@markt-asf  was this just an oversight or is it intentionally left out of the table?

https://jakarta.ee/specifications/servlet/6.1/jakarta-servlet-spec-6.1#request-attributes

**Comment by markt-asf** [comment]
Oversight

**Comment by pnicolucci** [comment]
@markt-asf PR is up, I'll backport to 6.1 once you take a look. Thanks!
