### ISSUE TITLE
TCK: Missing  filter resource in the `RegistrationTests` deployment

### ISSUE THREAD

**Issue by jamezp** [jakartaee/servlet#734]
**Challenged tests**
`servlet.tck.pluggability.api.jakarta_servlet.registration.RegistrationTests`

**TCK Version**
6.1.0

**Tested Implementation**
Undertow/WildFly

**Description**
The test is missing the `servlet.tck.api.jakarta_servlet.servletcontext30.AddFilterString` in the deployment. The `servlet.tck.api.jakarta_servlet.registration.TestListener` is added to the deployment which adds the filter manually.

The `@Deployment` method simply just needs to include this type in the deployment. I will follow up with a PR.

This is similar to #691

**Comment by olamy** [comment]
out of curiosity what sort of WildFly are you using? remote?
because obviously there is no issue with embedded Jetty.

**Comment by jamezp** [comment]
Just standalone WildFly 34 Preview. Any embedded server would not have an issue because the class would be on the class path. However, when the deployment is done it fails with a `ClassNotFoundException`, because the type is on on the class path.
